services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    env_file:
      - ./backend/postgre.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
