version: "3.9"

services:
  backend:
    build:
      context: ./backend
    image: hikaru20356/backend:${VERSION}
    env_file:
      - ./backend/.env.example
    command: sh -c "npm ci && npm run build"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    image: hikaru20356/frontend:${VERSION}
    command: sh -c "npm ci && npm run build"

  nginx:
    build:
      context: ./nginx
    image: hikaru20356/nginx:${VERSION}

  postgres:
    image: postgres:16
    env_file:
      - ./backend/postgre.env.example
