apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-env
  namespace: app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-env
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: student-timetable/backend1
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: student-timetable/backend1
        property: JWT_SECRET
    - secretKey: NODE_ENV
      remoteRef:
        key: student-timetable/backend1
        property: NODE_ENV
    - secretKey: PORT
      remoteRef:
        key: student-timetable/backend1
        property: PORT
    - secretKey: CORS_ORIGIN
      remoteRef:
        key: student-timetable/backend1
        property: CORS_ORIGIN